"""
Run this script ONCE (with internet access) to download the real SAUSA300
deoC1 and deoC2 protein sequences from NCBI and write seqs_deoC.py.

Usage:
    python fetch_deoC_seqs.py
"""
from Bio import Entrez, SeqIO
import textwrap, sys

Entrez.email = "paul.torrillo@gmail.com"

TARGETS = {
    "SAUSA300_0140_deoC1": "ABD20584.1",   # UniProt Q2FHN2
    "SAUSA300_2090_deoC2": "ABD22534.1",   # UniProt Q2FDU4
}

# Genomic coordinates on CP000255.1 (USA300_FPR3757, 2,872,769 bp)
COORDS = {
    "SAUSA300_0140_deoC1": dict(start=154_822, end=155_481, strand=-1),
    "SAUSA300_2090_deoC2": dict(start=2_379_982, end=2_380_641, strand=+1),
}

seqs = {}
for label, acc in TARGETS.items():
    print(f"Fetching {label} ({acc}) …", end=" ", flush=True)
    try:
        h = Entrez.efetch(db="protein", id=acc, rettype="fasta", retmode="text")
        rec = SeqIO.read(h, "fasta")
        h.close()
        seqs[label] = str(rec.seq)
        print(f"OK  ({len(rec.seq)} AA)")
    except Exception as e:
        print(f"FAILED: {e}")
        sys.exit(1)

lines = ['"""Auto-generated by fetch_deoC_seqs.py – do not edit by hand."""\n']
lines.append("GENOME_LEN  = 2_872_769\n")
for label, coord in COORDS.items():
    lines.append(
        f"{label.upper()}_START  = {coord['start']}\n"
        f"{label.upper()}_END    = {coord['end']}\n"
        f"{label.upper()}_STRAND = {coord['strand']}\n"
    )
for label, seq in seqs.items():
    wrapped = '"\n    "'.join(textwrap.wrap(seq, 60))
    lines.append(f'{label.upper()}_SEQ = (\n    "{wrapped}"\n)\n')

with open("seqs_deoC.py", "w") as fh:
    fh.writelines(lines)

print("\nWrote seqs_deoC.py  — re-run figure_deoC_alignment.py to regenerate the figure.")
